services:
  postgres_primary:
    image: postgres:16-alpine
    container_name: kuimakulakcontainer_v2
    restart: unless-stopped
    environment:
      POSTGRES_USER: prod_admin
      POSTGRES_PASSWORD: pass123!
      POSTGRES_DB: kuimakulak
    ports:
      - "5434:5432"
    volumes:
      - postgres_primary_data:/var/lib/postgresql/data
    networks:
      - my_network
  ## elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

networks:
  my_network:
    driver: bridge

volumes:
  postgres_primary_data: