services:
  postgres_primary:
    image: postgres:16-alpine
    container_name: kuimakulakcontainer
    restart: unless-stopped
    environment:
      POSTGRES_USER: prod_admin
      POSTGRES_PASSWORD: pass123!
      POSTGRES_DB: userdb
    ports:
      - "5434:5432"
    volumes:
      - postgres_primary_data:/var/lib/postgresql/data
    networks:
      - my_network
networks:
  my_network:
    driver: bridge

volumes:
  postgres_primary_data: