spring:
  application:
    name: KuimaKulak
  datasource:
    url: jdbc:postgresql://localhost:5434/kuimakulak
    username: prod_admin
    password: pass123!
    driver-class-name: org.postgresql.Driver