spring:
  application:
    name: KuimaKulak
  datasource:
    url: jdbc:postgresql://localhost:5432/kuima_kulak
    username: postgres
    password: nurs123
    driver-class-name: org.postgresql.Driver



app:
  base-url: http://localhost:8080