spring:
  application:
    name: KuimaKulak

  datasource:
        url: jdbc:postgresql://localhost:5432/kuima_kulak
        username: postgres
        password: nurs123
        driver-class-name: org.postgresql.Driver
  jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
  server:
      port: 8181
      error:
        include-message: always
  elasticsearch:
    uris: http://elasticsearch:9200
    connection-timeout: 1s
    socket-timeout: 30s