spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 100MB
      max-request-size: 105MB
  application:
    name: KuimaKulak
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ## migration
  liquibase:
    change-log: db/changelog/main-changelog.yaml
    enabled: false
  profiles:
    active: prod
  ##elasticsearch
  elasticsearch:
    uris: http://localhost:9200


app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 864000000
    refresh-token:
      expiration-ms: 15552000000

server:
  port: 8080



logging:
  level:
    org.springframework.security.oauth2: DEBUG

cloud:
  aws:
    credentials:
      access-key: AKIAROR2VEODLMK37XVN
      secret-key: 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
    region:
      static: eu-north-1
    s3:
      bucket: kuima-kulak

user:
  default:
    avatar: https://kuima-kulak.s3.eu-north-1.amazonaws.com/f6a19d2f-c262-4457-8daf-bb8d9bd23e92_Persoanl.png

